---
- hosts: localhost
  tasks:
    - include_role:
        name: cloud
- hosts: webservers
  vars:
    ansible_ssh_private_key_file: /home/ec2-user/environment/my-key.pem
  become: True
  gather_facts: True
  remote_user: ec2-user
  tasks:
    - include_role:
        name: webstack