---
- name: ensure apache is at the latest version
  yum:
    name: httpd
    state: latest
- name: ensure apache is running
  service:
    name: httpd
    state: started
- name: Templating the httpd.conf
  template:
    src: /home/ec2-user/environment/httpd.j2
    dest: /etc/httpd/conf.d/httpd.conf
  notify: restart apache
- copy:
    src: files/index.html
    dest: /var/www/html/index.html